Page rank algorithm support
petgraph/petgraph pull request #623
Opened 2024-03-30 09:24 UTC by geosarr

2024-04-01 12:46 UTC, ABorgna requested changes
Thanks!
I just have some change request.

2024-04-01 12:46 UTC, ABorgna commented on src/algo/mod.rs
> +pub trait UnitMeasure:
Add docs to the trait

2024-04-01 12:46 UTC, ABorgna commented on src/algo/page_rank.rs
> +    assert!(node_count > 0, "Graph must have nodes.");
We could return an empty vector here instead of panicking.

2024-04-01 12:46 UTC, ABorgna commented on src/algo/page_rank.rs
> +/// ```
Broken docs.

2024-04-01 19:51 UTC, ABorgna commented on src/algo/page_rank.rs
> +    assert!(node_count > 0, "Graph must have nodes.");
```suggestion
    if node_count == 0 {
        return vec![];
    }
```

2024-04-01 19:51 UTC, ABorgna commented on src/algo/page_rank.rs
> +/// \[Generic\] Parrallel Page Rank algorithm.
```suggestion
/// \[Generic\] Parallel Page Rank algorithm.
///
/// See [`page_rank`].
```

2024-04-01 20:50 UTC, ABorgna approved these changes

2024-04-01 20:57 UTC, merged

2024-04-02 00:42 UTC, geosarr commented
Thanks @ABorgna