fix adjacency matrix for csr and adjacency list
petgraph/petgraph pull request #648
Opened 2024-06-14 04:39 UTC by BryanCruz

hi folks, I was using the `GetAdjacencyMatrix` trait in a personal project and found out that the current trait implementations in `CSR` and `List` weren't working as expected, so I'm raising this PR to address that

I also added some tests for graph types where this trait is implemented

2024-12-23 13:37 UTC, XVilka requested changes
Thanks for the PR! Could you please rebase it? Also please update the PR description to describe what *exactly* was not working properly and is now fixed.

2024-12-23 18:00 UTC, BryanCruz commented
> Thanks for the PR! Could you please rebase it? Also please update the PR description to describe what _exactly_ was not working properly and is now fixed.

thanks for the review, made the requested changes

2024-12-28 18:06 UTC, XVilka approved these changes

2024-12-28 18:06 UTC, XVilka commented
@starovoid please take a look too

2024-12-28 18:24 UTC, starovoid commented
@XVilka 
It's definitely worth doing a new rebase. It also seems to me correct to split all the test functions into two parts, because the code below covers two non-trivial cases.

2024-12-28 18:33 UTC, XVilka commented
> @XVilka It's definitely worth doing a new rebase. It also seems to me correct to split all the test functions into two parts, because the code below covers two non-trivial cases.
> 
> ```rust
> test_adjacency_matrix(&directed_g);
> test_adjacency_matrix(&undirected_g);
> ```

Good idea! @BryanCruz please address this.

2024-12-28 21:29 UTC, BryanCruz commented
@XVilka @starovoid done

2024-12-29 16:05 UTC, XVilka approved these changes

2024-12-29 16:06 UTC, merged